[build]
  base = "culixo"
  command = "CI=false npm run build"  # Added CI=false to bypass some warnings
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "false"  # Added this to bypass some warnings

[functions]
  directory = "netlify/functions"